kind: Service
apiVersion: v1
metadata:
  name: cv2-xkilian-ambulance-ufe
spec:
  selector:
    pod: cv2-xkilian-ambulance-ufe-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
