apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv2-xkilian-ambulance-ufe-content
spec:
  microFrontend: cv2-xkilian-ambulance-ufe
  element: cv2-xkilian-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?cv2-xkilian-wl(/.*)?$"
