apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: kili5/ambulance-ufe
    newName: kili5/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20250324.1031 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
